### ISSUE TITLE
Please enable downloading from 3rd-party launchers!

### ISSUE THREAD

**Issue by LeoDog896** [MrUnknown404/Dice#2]
(Reference: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c)

Many modpacks now depend on your Dice mod, and adding 3rd party downloading can easily make modpacks that include your mod more accessible in general! I hope you consider this.

**Comment by MrUnknown404** [comment]
It's complicated and not something I wish to talk about. (hence why I've just kinda ignored anyone who asked and hoped they'd give up) but the simple reason is I'm unnecessarily stubborn and hate everything I've made and don't want to touch it.

**Comment by LeoDog896** [comment]
(sorry for the late response) i see -- thanks for responding!

**Comment by LeoDog896** [comment]
By any chance, would you mind if I forked and updated this project?

**Comment by MrUnknown404** [comment]
You're more then welcome to create the same thing from scratch but I'd prefer if my mod remained untouched. Sorry

**Comment by LeoDog896** [comment]
All good, thanks though!
