### ISSUE TITLE
Mod Not Available in New CurseForge API Breaking External Tools

### ISSUE THREAD

**Issue by Commandcracker** [MrUnknown404/Dice#3]
> The setting permitting the project to be accessible through the new CurseForge API is disabled which breaks the use of certain tools such as Packwiz. Toggling this setting to on will correct the issue, permitting the project to be downloaded through the new CurseForge API.
> 
> https://packwiz.infra.link/
https://github.com/packwiz/packwiz
> 
> ![image](https://user-images.githubusercontent.com/49335821/208927053-4ac18b97-ef57-4b2c-9e6e-0ad6060ffbec.png)

Quote from @coryjreid [Lupicus/SpawnerFix/issues/2](https://github.com/Lupicus/SpawnerFix/issues/2)

**Comment by jerkery678** [comment]
Why won't fix tho ;-;

**Comment by jerkery678** [comment]
I think it wouldn't hurt a lot and people can access these easily, since most people use third party launchers and the fact is that most downloads come from people browsing thorugh the site, rather than the people using modpacks.
